name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    name: Format, Build, Publish
    runs-on: ubuntu-latest
    steps:
      - uses: titanom/github-composite-actions/turbo/setup@v1.0.12
        with:
          pnpm-version: 8

      - name: Format
        run: pnpm format:check

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
